// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: locations.sql

package store

import (
	"context"

	uuid "github.com/google/uuid"
)

const createLocation = `-- name: CreateLocation :one
INSERT INTO locations (customer_id, parent_id, type, name, notes)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, customer_id, parent_id, type, name, notes, created_at, updated_at
`

type CreateLocationParams struct {
	CustomerID uuid.UUID    `json:"customer_id"`
	ParentID   *uuid.UUID   `json:"parent_id"`
	Type       LocationType `json:"type"`
	Name       string       `json:"name"`
	Notes      *string      `json:"notes"`
}

func (q *Queries) CreateLocation(ctx context.Context, arg CreateLocationParams) (Location, error) {
	row := q.db.QueryRow(ctx, createLocation,
		arg.CustomerID,
		arg.ParentID,
		arg.Type,
		arg.Name,
		arg.Notes,
	)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.ParentID,
		&i.Type,
		&i.Name,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listLocations = `-- name: ListLocations :many
SELECT id, customer_id, parent_id, type, name, notes, created_at, updated_at FROM locations
WHERE customer_id = $1
ORDER BY created_at, id
LIMIT $2 OFFSET $3
`

type ListLocationsParams struct {
	CustomerID uuid.UUID `json:"customer_id"`
	Limit      int32     `json:"limit"`
	Offset     int32     `json:"offset"`
}

func (q *Queries) ListLocations(ctx context.Context, arg ListLocationsParams) ([]Location, error) {
	rows, err := q.db.Query(ctx, listLocations, arg.CustomerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Location
	for rows.Next() {
		var i Location
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.ParentID,
			&i.Type,
			&i.Name,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
