// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package store

import (
	"database/sql/driver"
	"fmt"
	"time"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type FileKind string

const (
	FileKindImage    FileKind = "image"
	FileKindReceipt  FileKind = "receipt"
	FileKindDocument FileKind = "document"
)

func (e *FileKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FileKind(s)
	case string:
		*e = FileKind(s)
	default:
		return fmt.Errorf("unsupported scan type for FileKind: %T", src)
	}
	return nil
}

type NullFileKind struct {
	FileKind FileKind `json:"file_kind"`
	Valid    bool     `json:"valid"` // Valid is true if FileKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFileKind) Scan(value interface{}) error {
	if value == nil {
		ns.FileKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FileKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFileKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FileKind), nil
}

type ItemCondition string

const (
	ItemConditionNew  ItemCondition = "new"
	ItemConditionGood ItemCondition = "good"
	ItemConditionFair ItemCondition = "fair"
	ItemConditionPoor ItemCondition = "poor"
)

func (e *ItemCondition) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ItemCondition(s)
	case string:
		*e = ItemCondition(s)
	default:
		return fmt.Errorf("unsupported scan type for ItemCondition: %T", src)
	}
	return nil
}

type NullItemCondition struct {
	ItemCondition ItemCondition `json:"item_condition"`
	Valid         bool          `json:"valid"` // Valid is true if ItemCondition is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullItemCondition) Scan(value interface{}) error {
	if value == nil {
		ns.ItemCondition, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ItemCondition.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullItemCondition) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ItemCondition), nil
}

type LocationType string

const (
	LocationTypeArea        LocationType = "area"
	LocationTypeBuilding    LocationType = "building"
	LocationTypeFloor       LocationType = "floor"
	LocationTypeRoom        LocationType = "room"
	LocationTypeRack        LocationType = "rack"
	LocationTypeCabinet     LocationType = "cabinet"
	LocationTypeBox         LocationType = "box"
	LocationTypeCompartment LocationType = "compartment"
	LocationTypeVehicle     LocationType = "vehicle"
	LocationTypeOther       LocationType = "other"
)

func (e *LocationType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LocationType(s)
	case string:
		*e = LocationType(s)
	default:
		return fmt.Errorf("unsupported scan type for LocationType: %T", src)
	}
	return nil
}

type NullLocationType struct {
	LocationType LocationType `json:"location_type"`
	Valid        bool         `json:"valid"` // Valid is true if LocationType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLocationType) Scan(value interface{}) error {
	if value == nil {
		ns.LocationType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LocationType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLocationType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LocationType), nil
}

type Customer struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Email     *string   `json:"email"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type File struct {
	ID         uuid.UUID  `json:"id"`
	CustomerID uuid.UUID  `json:"customer_id"`
	ItemID     *uuid.UUID `json:"item_id"`
	Kind       FileKind   `json:"kind"`
	Filename   string     `json:"filename"`
	Path       string     `json:"path"`
	MimeType   *string    `json:"mime_type"`
	SizeBytes  *int64     `json:"size_bytes"`
	CreatedAt  time.Time  `json:"created_at"`
}

type Item struct {
	ID                 uuid.UUID         `json:"id"`
	CustomerID         uuid.UUID         `json:"customer_id"`
	LocationID         uuid.UUID         `json:"location_id"`
	Name               string            `json:"name"`
	Notes              *string           `json:"notes"`
	Quantity           int32             `json:"quantity"`
	FillLevel          *int32            `json:"fill_level"`
	Capacity           pgtype.Numeric    `json:"capacity"`
	Condition          NullItemCondition `json:"condition"`
	DateAcquired       pgtype.Date       `json:"date_acquired"`
	PurchasePriceCents *int64            `json:"purchase_price_cents"`
	CreatedAt          time.Time         `json:"created_at"`
	UpdatedAt          time.Time         `json:"updated_at"`
}

type Location struct {
	ID         uuid.UUID    `json:"id"`
	CustomerID uuid.UUID    `json:"customer_id"`
	ParentID   *uuid.UUID   `json:"parent_id"`
	Type       LocationType `json:"type"`
	Name       string       `json:"name"`
	Notes      *string      `json:"notes"`
	CreatedAt  time.Time    `json:"created_at"`
	UpdatedAt  time.Time    `json:"updated_at"`
}
